name: FRC Build & Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1.1.1
    - name: FRC Build & Test
      uses: ewpratten/FRC-actions@v1
      with:
        build_mode: 'build'